---
title: "Liberia maps"
date: "`r format(Sys.Date(), format='%A, %B %d, %Y')`"
output: rmarkdown::github_document
---

```{r data-prep, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, eval=TRUE}
library(rgdal)

adm_all <- "lbr-administrative-divisions-shapefiles/lbr_adm_ocha_20191104_SHP/lbr_admbndl_admALL_ocha_itos_20191104.shp"
adm0 <- "lbr-administrative-divisions-shapefiles/lbr_adm_ocha_20191104_SHP/lbr_admbnda_adm0_ocha_20191104.shp"
adm1 <- "lbr-administrative-divisions-shapefiles/lbr_adm_ocha_20191104_SHP/lbr_admbnda_adm1_ocha_20191104.shp"
adm2 <- "lbr-administrative-divisions-shapefiles/lbr_adm_ocha_20191104_SHP/lbr_admbnda_adm2_ocha_20191104.shp"

# fin <- "hotosm_liberia_financial_services_points_shp/hotosm_liberia_financial_services_points.shp"
```

## Liberia boundary

```{r liberia-boundary, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, eval=TRUE}
adm0_shp <- readOGR(adm0, verbose = FALSE)
plot(adm0_shp)
```

## County boundaries

```{r county-boundaries, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, eval=TRUE}
adm1_shp <- readOGR(adm1, verbose = FALSE)
plot(adm1_shp)
```

## District boundaries

```{r district-boundaries, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, eval=TRUE}
adm2_shp <- readOGR(adm2, verbose = FALSE)
plot(adm2_shp)
```

Source: [Humanitarian Data Exchange](https://data.humdata.org/m/dataset/liberia-admin-level-2-boundaries)
